# .github/workflows/demo-pipeline.yml
name: Demo CI/CD Pipeline
 
on:
  workflow_dispatch:
    
 
jobs:
  test:
    name: ğŸ§ª Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Print test step
        run: echo "Running tests... âœ…"
 
  build:
    name: ğŸ—ï¸ Build Application
    runs-on: ubuntu-latest
    needs: test     # This job runs only if "test" job is successful
    steps:
      - name: Print build step
        run: echo "Building the application... ğŸ”¨"
 
  deploy:
    name: ğŸš€ Deploy Application
    runs-on: ubuntu-latest
    needs: build    # This job runs only if "build" job is successful
    steps:
      - name: Print deploy step
        run: echo "Deploying the application... ğŸš€"
